entities:

  # Antibody target
  - file:
      path: 8E8Z.cif

      include:
        - chain:
            id: E   # heavy
        - chain:
            id: F   # light

      binding_types:
        - chain:
            id: E
            binding: 100..104,106..109  #shifted -21
        - chain:
            id: F
            binding: 25,26,30,54,94,95  #shifted -20

      structure_groups:
        - group:
            id: E
            visibility: 1
        - group:
            id: F
            visibility: 1


# Designed miniprotein scaffold
  - protein:
      id: P
      sequence: 80..140

  # VP1 epitope residues fused into scaffold
  - file:
      path: 8E8Z.cif
      fuse: P

      include:
        - chain:
            id: A
            res_index: 81,84,85,86,147   # VP1 epitope (shifted -21)
      binding_types:
        - chain:
            id: A
            binding: "all"


  # VP2 epitope residues fused into scaffold
  - file:
      path: 8E8Z.cif
      fuse: P

      include:
        - chain:
            id: B
            res_index: 130,133   # VP2 epitope (shifted -9)
      binding_types:
        - chain:
            id: B
            binding: "all"